import type { Metadata } from "next";
import { Roboto} from "next/font/google";
import "../../globals.css";
import Header from '@/components/header'
import ReduxProvider from "@/providers/ReduxProvider";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";

const roboto = Roboto({
  subsets: ["latin"],
  weight:["400","600","800"],
  preload:true
});

console.log('roboto.className'+ roboto.className)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
  // params:Promie<locale:Locale>
}>) {
  // const pathname = usePathname()

  return (
    
      <NextAuthSessionProvider>

      <ReduxProvider>

       <Header />
        {children}
      </ReduxProvider>
      </ NextAuthSessionProvider>

   
  );
}
