import type { Metadata } from "next";
import { Geist, Geist_Mono ,Roboto} from "next/font/google";
import "./globals.css";
import Header from '@/components/header'
import Footer from '@/components/footer'


const roboto = Roboto({
  subsets: ["latin"],
  weight:["400","600","800"],
  preload:true
});

console.log('roboto.className'+roboto.className)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={roboto.className}
      >
        <Header></Header>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
