import Footer from '@/components/footer';
import ReduxProvider from '@/providers/ReduxProvider';
import type { ReactNode } from 'react';
import "../[locale]/globals.css"
import { Languages } from '@/constants/enums';
import { Roboto } from 'next/font/google';
import { Locale } from '@/i18n.config';
import { Metadata } from 'next';

  const roboto = Roboto({
    subsets: ["latin"],
    weight:["400","600","800"],
    preload:true
  }); 
 
  export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function HomeLayout({ children,params }: { children: ReactNode,  params:Promise<{locale:Locale}>
 }) {


    const locale=(await params).locale
    const dir=locale==Languages.ARABIC?'rtl':'ltr'
    return (
      <html lang={locale} dir={dir}>
        <body
          className={roboto.className}
        >
      
              <ReduxProvider>
        
                {children}
                <Footer />
              </ReduxProvider>
                
      </body>
    </html>
  );
}



