import Footer from "@/components/footer";
import ReduxProvider from "@/providers/ReduxProvider";
import type { ReactNode } from "react";
import "../[locale]/globals.css";
import { Languages } from "@/constants/enums";
import { Roboto } from "next/font/google";
import { Locale } from "@/i18n.config";
import { Metadata } from "next";
import { Toaster } from "@/components/ui/Toast";
import NextAuthSessionProvider from "@/providers/NextAuthSessionProvider";

// import 'src/app/[locale]/globals.css'

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "600", "800"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function HomeLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: Promise<{ locale: Locale }>;
}) {
  const locale = (await params).locale;
  const dir = locale == Languages.ARABIC ? "rtl" : "ltr";
  return (
    <html lang={locale} dir={dir}>
      <body className={roboto.className}>
        <NextAuthSessionProvider>
        <ReduxProvider>
          {children}
          <Toaster className="text-red-500 bg-red-50" />

          <Footer />
        </ReduxProvider>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
