import type { Metadata } from "next";
import { Geist, Geist_Mono ,Roboto} from "next/font/google";
import "./globals.css";
import Header from '@/components/header'
import Footer from '@/components/footer'
import ReduxProvider from "@/providers/ReduxProvider";
import { Locale } from "@/i18n.config";
import { Languages } from "@/constants/enums";


const roboto = Roboto({
  subsets: ["latin"],
  weight:["400","600","800"],
  preload:true
});

console.log('roboto.className'+roboto.className)

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,params
}: Readonly<{
  children: React.ReactNode;
  params:Promise<{locale:Locale}>
}>) {
  const locale=(await params).locale
  const dir=locale==Languages.ARABIC?'rtl':'ltr'
  return (
    <html lang={locale} dir={dir}>
      <body
        className={roboto.className}
      >
      <ReduxProvider>

        <Header></Header>
        {children}
        <Footer/>
      </ReduxProvider>

      </body>
    </html>
  );
}
